### ISSUE TITLE
"Many faces" tracking issue

### ISSUE THREAD

**Issue by summertriangle-dev** [summertriangle-dev/sparklebox#3]
I'm going to let users play with sprite faces eventually.

- [x] Add faces to GX want list
- [x] Figure out how to use the chara_face_positions.
- [x] Generate metadata for image server
- [x] Make the viewer page
  - [x] Load data from server
  - [x] Display each eligible pose
  - [x] Make faces selectable and in correct position
  - [x] Clean up
